### ISSUE TITLE
误伤率挺高的

### ISSUE THREAD

**Issue by barry1006** [fengzuo97/pyec#1]
这一路的泥泞像黑潮般涌动
[8, '超']
拼  是我命数中必有的波动
[0, '平']
这每一次的栽倒 都有嘲讽声
[1, '枚']
这每一次用汗洗掉内心的惶恐
[5, '航']
胜败早已没资格
[0, '审']
左右我心中晴空
[5, '清']
带着笑面对逆风
[5, '你']
撑着多年拼搏的梦
[0, '趁']
你就该坚强的选择重生
[8, '中']
我就敢挑起事端不怕痛
[9, '同']
痛过也该有笑容
[0, '通']
享受这追逐的过程
[2, '着']
此生当再回首 仰望着星空
[10, '新']
你定会为曾傻气的你眼红
[0, '拟']

**Comment by fengzuo97** [comment]
你这个测试的语句应该是来自诗歌的，会有一些歧义，训练语言的语料使用诗歌的语料应该会好些。用ngram语言模型来纠错的话，可以通过参数的调整来降低误伤率。

**Comment by barry1006** [comment]
嗯。  感觉主要的原因是采用字粒度的分词来给中文做纠错，误伤率会比较高。  中文的每个词，是单个字或者多个字。  
我现在用搜狗的语料训练一下，使用词粒度的分词，  然后再用分词之后的文本制作语言模型。
目前测试结果显示，  词粒度分词后， 误伤率降低了。


------------------
 Best Regards,
yangzzhao 赵阳 Barry Z.
Tencent
 Mobile:18503058640




 




------------------ Original ------------------

**Comment by fengzuo97** [comment]
pycorrector的作者也提到了，不过我的测试结果是字级模型比词级模型查全率会高些。
